require "json"

package = JSON.parse(File.read(File.join(__dir__, "../package.json")))
version = package['dependencies']["doric"]
version = version.gsub('^','')

source 'https://cdn.cocoapods.org/'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'V2EX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'DoricCore', "#{version}"
  pod 'DoricDevkit', "#{version}"
end
