# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'V2EX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'DoricCore', '~>0.3.26'
  pod 'DoricDevkit', '~>0.3.26'
end
